# Generated by Django 6.1.1 on 2026-09-09 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a valid 6-digit pincode.')])),
                ('block', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pincode'], name='users_locat_pincode_39cc93_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number.')])),
                ('education', models.CharField(choices=[('no_education', 'No Education'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary'), ('graduate_and_above', 'Graduate and above')], max_length=30)),
                ('photograph', models.ImageField(upload_to='profiles/photos/')),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('no_of_projects', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_households_touched', models.PositiveIntegerField(blank=True, null=True)),
                ('key_projects', models.TextField(blank=True)),
                ('impact_stories_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trust_level_notes', models.TextField(blank=True)),
                ('audio_intro', models.FileField(blank=True, null=True, upload_to='profiles/audio/')),
                ('badge', models.CharField(blank=True, choices=[('lead', 'Lead CDE'), ('advanced', 'Advanced CDE'), ('active', 'Active CDE'), ('emerging', 'Emerging CDE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(related_name='profiles', to='users.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.location')),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='users.skill')),
            ],
        ),
    ]
