# Generated by Django 6.1.1 on 2026-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.CharField(choices=[('Lead CDE', 'Lead CDE'), ('Advanced CDE', 'Advanced CDE'), ('Active CDE', 'Active CDE'), ('Emerging CDE', 'Emerging CDE')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('No Education', 'No Education'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Graduate and above', 'Graduate and above')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
