# Generated by Django 6.1.1 on 2026-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fix_badge_level_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Expert', 'Expert'), ('Practitioner', 'Practitioner'), ('Learner', 'Learner')], max_length=100, unique=True),
        ),
    ]
