# Generated by Django 6.1.1 on 2026-09-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_block_district_state_remove_location_district_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('block', 'pincode')},
        ),
    ]
