# Generated by Django 6.1.1 on 2026-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_location_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badge',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('Lead CDE', 'Lead CDE'), ('Advanced CDE', 'Advanced CDE'), ('Active CDE', 'Active CDE'), ('Emerging CDE', 'Emerging CDE')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
