# Generated by Django 6.1.1 on 2026-09-09 16:35

import django.db.models.deletion
from django.db import migrations, models

TITLES = ["Mentor", "Expert", "Practitioner", "Learner"]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model("users", "Badge")
    Badge.objects.bulk_create([Badge(title=title) for title in TITLES], ignore_conflicts=True)


def unseed_badges(apps, schema_editor):
    Badge = apps.get_model("users", "Badge")
    Badge.objects.filter(title__in=TITLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_badge_userprofile_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mentor', 'Mentor'), ('Expert', 'Expert'), ('Practitioner', 'Practitioner'), ('Learner', 'Learner')], max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(seed_badges, unseed_badges),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.badge'),
        ),
    ]
