# Generated by Django 6.1.1 on 2026-09-10 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_annual_operating_budget'),
        ('users', '0011_badge_remove_userprofile_level_userprofile_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
