# Generated by Django 6.1.1 on 2026-09-17 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_tool_organizationtool_organization_tools_usertool'),
        ('users', '0013_userprofile_is_phone_verified_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('org_admin', 'Org Admin'), ('coordinator', 'Coordinator'), ('cde', 'CDE')], default='cde', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('No Education', 'No Education'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Graduate and above', 'Graduate and above')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
    ]
