# Generated by Django 6.1.1 on 2026-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_location_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_established', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('sector_other_detail', models.CharField(blank=True, max_length=255)),
                ('beneficiary_group_other_detail', models.CharField(blank=True, max_length=255)),
                ('annual_beneficiaries_reached', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_operating_budget', models.CharField(blank=True, choices=[('< ₹50 lakh', '< ₹50 lakh'), ('₹50 lakh – ₹2 crore', '₹50 lakh – ₹2 crore'), ('₹2 crore – ₹5 crore', '₹2 crore – ₹5 crore'), ('> ₹5 crore', '> ₹5 crore')], max_length=30)),
                ('total_team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('field_staff_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_groups', models.ManyToManyField(blank=True, related_name='organizations', to='organizations.beneficiarygroup')),
                ('states_of_operation', models.ManyToManyField(blank=True, related_name='organizations', to='users.state')),
                ('sectors', models.ManyToManyField(blank=True, related_name='organizations', to='organizations.sector')),
            ],
        ),
    ]
