# Generated by Django 6.1.1 on 2026-09-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_sectors_and_beneficiary_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='annual_operating_budget',
            field=models.CharField(blank=True, choices=[('< ₹50 lakh', '< ₹50 lakh'), ('₹50 lakh - ₹2 crore', '₹50 lakh - ₹2 crore'), ('₹2 crore - ₹5 crore', '₹2 crore - ₹5 crore'), ('> ₹5 crore', '> ₹5 crore')], max_length=30),
        ),
    ]
