# Generated by Django 6.1.1 on 2026-09-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_annual_operating_budget'),
        ('users', '0013_userprofile_is_phone_verified_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('moderation-interface', 'Moderation Interface'), ('case-manager', 'Case Manager'), ('dist-mod', 'Dist Mod')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_tools_granted', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_grants', to='organizations.organization')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_grants', to='organizations.tool')),
            ],
            options={
                'unique_together': {('organization', 'tool')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='organizations', through='organizations.OrganizationTool', to='organizations.tool'),
        ),
        migrations.CreateModel(
            name='UserTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tools_granted', to='users.userprofile')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='organizations.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_grants', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
